### ISSUE TITLE
能否给Python版本提供一个包含ghostscript的公共层？

### ISSUE THREAD

**Issue by unfish** [awesome-fc/awesome-layers#37]
因为基础层已经包含了Wand，也自动包含了imagemagick，我以为可以直接用，但是通过Wand打开PDF文件的时候会报错。我根据这个demo里的dockerfile修改成本地安装ghostscript然后打包一个中间层传上去不管用，它还是识别不了/opt里面的东西，手动登录进去运行convert文件格式转换命令也会报错，找不到gs执行文件等，估计是ghostscript这个东西依赖底层的东西比较多，安装后打包一个zip文件方式不管用。

**Comment by lowkeyrd** [comment]
哪个demo？

**Comment by fanzhe328** [comment]
麻烦提供一下具体的测试代码，以及你制作依赖层的方法。包括制作层的dockerfile文件，项目的配置，验证的方法

**Comment by fanzhe328** [comment]
我这边测试没有问题，直接在官网下载 ghostscript （https://ghostscript.com/releases/gsdnld.html），版本是 Ghostscript 10.0.0 for Linux x86 (64 bit)，在自定义运行时（debian10）内可以直接执行
请提供具体的报错信息
![image](https://user-images.githubusercontent.com/3874077/220229613-ac05684a-bbd1-4862-a30d-8c7f5edb7ccc.png)
