### ISSUE TITLE
有没有 python 3.10 的 pytorch 和 tensorflow的公共层呢

### ISSUE THREAD

**Issue by nne998** [awesome-fc/awesome-layers#52]
如题

**Comment by fanzhe328** [comment]
已支持
- [Python310-PyTorch2x](https://github.com/awesome-fc/awesome-layers/blob/main/docs/Python310-PyTorch2x/README.md)
- [Python310-TensorFlow2x](https://github.com/awesome-fc/awesome-layers/blob/main/docs/Python310-TensorFlow2x/README.md)
