### ISSUE TITLE
Node18 公共层版本过低

### ISSUE THREAD

**Issue by 634750802** [awesome-fc/awesome-layers#53]
目前 node18 公共层 版本 18.3.0，next 13 server action 会出现以下错误:

```
- error TypeError: backingFormData.forEach is not a function
    at JSON.parse (<anonymous>)
    at Multipart.emit (node:events:527:28)
    at IncomingMessage.emit (node:events:527:28)
```

**Comment by 634750802** [comment]
@fanzhe328

**Comment by fanzhe328** [comment]
@634750802 
麻烦提供一下具体的复现方法，是需要升级nodejs18版本解决？

**Comment by 634750802** [comment]
@fanzhe328 
https://github.com/634750802/node18.3.0-error-reproduce

**Comment by 634750802** [comment]
https://nextjs.org/docs/app/api-reference/functions/server-actions

**Comment by 634750802** [comment]
升级应该可以解决这个问题

**Comment by 634750802** [comment]
@fanzhe328

**Comment by c0per** [comment]
请问是否考虑提升 `Node18` 的版本呢？[Next.js 14 支持的最低node版本](https://nextjs.org/blog/next-14#other-changes)为 `18.17`。

或者考虑提供 `Node19` 公共层？

**Comment by fanzhe328** [comment]
了解，我们会在本周升级Node18的版本

**Comment by fanzhe328** [comment]
@c0per 
新版本已发布，可以试用一下
`acs:fc:{region}:official:layers/Nodejs18/versions/3`
